### ISSUE TITLE
Preloading Images / Data outside preload()

### ISSUE THREAD

**Issue by kaosbeat** [ffd8/P5LIVE#135]
Hi,

Not sure if this is the right place for this, but this used to work in 1.6.2

I'm trying to dynamically load images outside the preload(), during draw().
I'm setting a global variable not to render the images until loading is done using a callback.
I have a series of images, which I store in a buffer

`imgdataset = []`

so basically, I pass in a series of urls (using a websocket connection) into my prepImgDataset function

```
function imgLoadDone(img){
    imgdataset.push(img)
    if (imgdataset.length == 6) {
        p5vars.imgloaderdone = true
    }

}
function prepImgDataset(imglist){
    loginfo("prepping img dataset")
    let i = 0;
    imgdataset = []
    p5vars.imgloaderdone = false
    imglist.forEach(imgpath => {
        let imageurl = dataURL + imgpath
        // console.log(imageurl)
        let prepimg = loadImage(imageurl, imgLoadDone)
        imgdataset[i] =  prepimg
        i++;
    })
    loginfo("done prepping img dataset")
    // return imgdataset    
}
```

 The images load fine, but I get a type error that is worrying  
`Uncaught TypeError: y._decrementPreload is not a function`  

I found some references to this error online, but no solution. Is this bad? This implementation used to work for me in a previous version of P5live (1.6.2 tested)

**Comment by kaosbeat** [comment]
Ok thanks for that, very useful. 
It did not fix it for now, but I'm moving on to ignoring the problem. I will report it at p5js though... I'll reference here
